/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sopa.de.letras;

import Estructuras_de_datos.Lista;


/**
 *Este es la segunda ventana que se genera despues de seleccionar el archivo diccionario.txt
 * Esta es la ventana que conecta todas las demas ventanas entre si
 * Esta da pie a la Ventana2, diccionary y Agregar_palabra
 * @author Diego Arreaza
 */

public class menu extends javax.swing.JFrame {
    /**
     *el atributo v1 contiene el contenido de la Ventana1
     */
    
    private static Ventana1 v1;
    /**
     * Constructor de la clase
     * Pone restriccione a la interface
     * @param v1 es la Ventana1
     */
    
    public menu(Ventana1 v1) {
        initComponents();
        menu.v1 = v1;
        this.setVisible(true);
        
    }
    
    /**
     *Retorna la Lista que contiene las palabra de diccionary.txt que creo la Ventana1
     * @return Lista que contiene palaras 
     */
    public Lista getlist_p(){
        return v1.get_palabras();
    }
    
    /**
     * Retorna la Lista que contiene las letras de diccionary.txt que creo la Ventana1
     * @return Lista que contiene letras 
     */
    public Lista getlist_l(){
        return v1.get_letras();
    }
    
    /**
     * metodo que llama al metodo de Agregar_palabra_diccionario de la v1
     */
    public void ag(){
        v1.Agregar_palabra_diccionario();
    }
    
    /**
     * metodo que vuelve a hacer visible a esta ventana
     */
    public void back(){
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        new_word = new javax.swing.JToggleButton();
        inicio = new javax.swing.JToggleButton();
        ver_palabras = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        new_word.setBackground(new java.awt.Color(255, 255, 255));
        new_word.setForeground(new java.awt.Color(0, 0, 0));
        new_word.setText("Agregar Palabra al Diccionario");
        new_word.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_wordActionPerformed(evt);
            }
        });
        jPanel1.add(new_word, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 490, 90));

        inicio.setBackground(new java.awt.Color(255, 255, 255));
        inicio.setForeground(new java.awt.Color(0, 0, 0));
        inicio.setText("Iniciar Sopa de Letras");
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        jPanel1.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 490, 90));

        ver_palabras.setBackground(new java.awt.Color(255, 255, 255));
        ver_palabras.setForeground(new java.awt.Color(0, 0, 0));
        ver_palabras.setText("Ver Diccionario");
        ver_palabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_palabrasActionPerformed(evt);
            }
        });
        jPanel1.add(ver_palabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 490, 80));

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setText("X");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 70, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("MENU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * metodo que da pie a Ventana2
     * @param evt
     */
    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Ventana2 v2 = new Ventana2(v1);
        
    }//GEN-LAST:event_inicioActionPerformed
    /**
        * metodo que da pie a Agregar_palabra
        *@param evt
     */
    private void new_wordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_wordActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Agregar_palabra a_p = new Agregar_palabra(this);
    }//GEN-LAST:event_new_wordActionPerformed
    /**
     * metodo que da pie a diccionary
     * @param evt
     */
    private void ver_palabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_palabrasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        diccionary p1 = new diccionary(this);
        
    }//GEN-LAST:event_ver_palabrasActionPerformed
    /**
     *  metodo que se activa al dar clic al boton jBurron1
     * metodo que cierra el programa
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new menu(v1).setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton new_word;
    private javax.swing.JToggleButton ver_palabras;
    // End of variables declaration//GEN-END:variables
}
