/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sopa.de.letras;


/**
 *
 * @author sl001
 */
public class menu extends javax.swing.JFrame {
    private static Ventana1 v1;
    /**
     * Creates new form menu
     */
    public menu(Ventana1 v1) {
        initComponents();
        this.v1 = v1;
        this.setVisible(true);
        this.setUndecorated(true);
        this.setExtendedState(6);
        
    }
    public Lista getlist(){
        return this.v1.get_palabras();
    }
    
    public void back(){
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        new_word = new javax.swing.JToggleButton();
        inicio = new javax.swing.JToggleButton();
        ver_palabras = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        new_word.setBackground(new java.awt.Color(255, 255, 255));
        new_word.setForeground(new java.awt.Color(0, 0, 0));
        new_word.setText("Agregar Palabra al Diccionario");
        new_word.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_wordActionPerformed(evt);
            }
        });
        jPanel1.add(new_word, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 490, 90));

        inicio.setBackground(new java.awt.Color(255, 255, 255));
        inicio.setForeground(new java.awt.Color(0, 0, 0));
        inicio.setText("Iniciar Sopa de Letras");
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        jPanel1.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 490, 90));

        ver_palabras.setBackground(new java.awt.Color(255, 255, 255));
        ver_palabras.setForeground(new java.awt.Color(0, 0, 0));
        ver_palabras.setText("Ver Diccionario");
        ver_palabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_palabrasActionPerformed(evt);
            }
        });
        jPanel1.add(ver_palabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 490, 80));

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setText("X");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 60, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Ventana2 v2 = new Ventana2(v1);
        
    }//GEN-LAST:event_inicioActionPerformed

    private void new_wordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_wordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_wordActionPerformed

    private void ver_palabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_palabrasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        diccionary p1 = new diccionary(this);
        
    }//GEN-LAST:event_ver_palabrasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new menu(v1).setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton new_word;
    private javax.swing.JToggleButton ver_palabras;
    // End of variables declaration//GEN-END:variables
}
