/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sopa.de.letras;
import metodos_de_busqueda.DFS;
import Estructuras_de_datos.Grafo;
import metodos_de_busqueda.BFS;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JTextField;
import org.graphstream.graph.Graph;

/**
 * clase de la Ventana principal deel programa el que muestra la sopa de letras y la que la resuelve
 * @author Diego Arreaza
 */
public class Ventana2 extends javax.swing.JFrame {
    
    /**
     * Atributos de la clase
     * v1 contiene a la clase que muestra a la primera ventana del proyecto
     * s_l es el grafo de la sopa de letras
     * metodo es el metodo de busqueda de la sopa de letras
     * words es la lista que contiene las palabras encontradas de la sopa de letra
     * tiempo es la lista que contiene el tiempo en que se tardo en buscar cada palabra de la sopa de letras
     */
    private static Ventana1 v1;
    private static Grafo s_l;
    private String metodo = "";
    private DefaultListModel<String> words = new DefaultListModel<>();
    private DefaultListModel<String> tiempo = new DefaultListModel<>();
    
    /**
     * Creates new form ventana2, jText.setText(words);
     * @param v1
     */
    public Ventana2( Ventana1 v1) {
        initComponents();
        Ventana2.v1 = v1;
        this.Crear_sopa_de_letras();
        this.setVisible(true);
    }
    
    public void Back(){
        this.setVisible(true);
    }
    
    /**
     * Este metodo que se encarga de colocar los colores a las letras que forman las palabras de la sopa de letras
     * @param x es un verificador para marcar de distinto color la palabra que el usuario haya escrito
     */
    private void colores(boolean x){
        JTextField[] aux = {this.letra1, this.letra2, this.letra3, this.letra4, this.letra5, this.letra6,this.letra7, this.letra8, this.letra9, this.letra10, this.letra11, this.letra12, this.letra13, this.letra14, this.letra15, this.letra16};
        for (int i = 0; i < 16; i++) {
            if (s_l.get_vertice(i).get_status()==true) {
                if (x== true) {
                    aux[i].setBackground(Color.YELLOW);
                }else{
                    aux[i].setBackground(Color.GREEN);
                }
                
            }
        }
    }
    
    /**
     * Este metodo se encarga de crear la sopa
     */
    private void Crear_sopa_de_letras(){
        s_l = new Grafo(v1.get_letras());
        JTextField[] aux = {this.letra1, this.letra2, this.letra3, this.letra4, this.letra5, this.letra6,this.letra7, this.letra8, this.letra9, this.letra10, this.letra11, this.letra12, this.letra13, this.letra14, this.letra15, this.letra16};
        for (int i = 0; i < 16; i++) {
            aux[i].setText(s_l.get_vertice(i).get_dato());
        }
    }
    
    /**
     * Este metodo se encarga de mostrar las palabras encontradas en la sopa de letras
     * @param p es la matriz con las palabras encontradas en la sopa de letras
     */
    private void mostrar_palabras(String[] p){
        for (String p1 : p) {
            if (p1 != null) {
                words.addElement(p1);   
            }
        }
        jList1.setModel(words);
    }
    
    /**
     * Este metodo se encarga de mostrar el tiempo en que se tardo en encontrar las palabras de la sopa de letras
     * @param t es la matriz con el tiempo que se encontro las palabras encontradas en la sopa de letras
     */
    private void mostrar_tiempo(double[] t){
        
        for (int i = 0; i < t.length; i++) {
            if(t[i] != 0.0){
                tiempo.addElement(Double.toString(t[i]));   
            }
        }
        jList2.setModel(tiempo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        palabras_sopa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        letra1 = new javax.swing.JTextField();
        letra2 = new javax.swing.JTextField();
        letra3 = new javax.swing.JTextField();
        letra4 = new javax.swing.JTextField();
        letra5 = new javax.swing.JTextField();
        letra6 = new javax.swing.JTextField();
        letra7 = new javax.swing.JTextField();
        letra8 = new javax.swing.JTextField();
        letra9 = new javax.swing.JTextField();
        letra10 = new javax.swing.JTextField();
        letra11 = new javax.swing.JTextField();
        letra12 = new javax.swing.JTextField();
        letra13 = new javax.swing.JTextField();
        letra14 = new javax.swing.JTextField();
        letra15 = new javax.swing.JTextField();
        letra16 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        Exit = new javax.swing.JButton();
        New_palabra = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        iniciar = new javax.swing.JButton();
        DFS = new javax.swing.JButton();
        BFS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextArea3 = new javax.swing.JTextArea();
        m_b = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        Alerta = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("sopa de letras");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        palabras_sopa.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        palabras_sopa.setForeground(new java.awt.Color(0, 0, 0));
        palabras_sopa.setText("Palabras de la Sopa de Letras");
        palabras_sopa.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(palabras_sopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 340, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        letra1.setEditable(false);
        letra1.setBackground(new java.awt.Color(255, 255, 255));
        letra1.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra1.setForeground(new java.awt.Color(0, 0, 0));
        letra1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra1.setText("X");
        jPanel2.add(letra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 120));

        letra2.setEditable(false);
        letra2.setBackground(new java.awt.Color(255, 255, 255));
        letra2.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra2.setForeground(new java.awt.Color(0, 0, 0));
        letra2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra2.setText("X");
        letra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra2ActionPerformed(evt);
            }
        });
        jPanel2.add(letra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 110, 120));

        letra3.setEditable(false);
        letra3.setBackground(new java.awt.Color(255, 255, 255));
        letra3.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra3.setForeground(new java.awt.Color(0, 0, 0));
        letra3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra3.setText("X");
        letra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra3ActionPerformed(evt);
            }
        });
        jPanel2.add(letra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 110, 120));

        letra4.setEditable(false);
        letra4.setBackground(new java.awt.Color(255, 255, 255));
        letra4.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra4.setForeground(new java.awt.Color(0, 0, 0));
        letra4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra4.setText("X");
        letra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra4ActionPerformed(evt);
            }
        });
        jPanel2.add(letra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 110, 120));

        letra5.setEditable(false);
        letra5.setBackground(new java.awt.Color(255, 255, 255));
        letra5.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra5.setForeground(new java.awt.Color(0, 0, 0));
        letra5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra5.setText("X");
        letra5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra5ActionPerformed(evt);
            }
        });
        jPanel2.add(letra5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 110, 120));

        letra6.setEditable(false);
        letra6.setBackground(new java.awt.Color(255, 255, 255));
        letra6.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra6.setForeground(new java.awt.Color(0, 0, 0));
        letra6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra6.setText("X");
        letra6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra6ActionPerformed(evt);
            }
        });
        jPanel2.add(letra6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 110, 120));

        letra7.setEditable(false);
        letra7.setBackground(new java.awt.Color(255, 255, 255));
        letra7.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra7.setForeground(new java.awt.Color(0, 0, 0));
        letra7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra7.setText("X");
        letra7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra7ActionPerformed(evt);
            }
        });
        jPanel2.add(letra7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 110, 120));

        letra8.setEditable(false);
        letra8.setBackground(new java.awt.Color(255, 255, 255));
        letra8.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra8.setForeground(new java.awt.Color(0, 0, 0));
        letra8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra8.setText("X");
        letra8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra8ActionPerformed(evt);
            }
        });
        jPanel2.add(letra8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 110, 120));

        letra9.setEditable(false);
        letra9.setBackground(new java.awt.Color(255, 255, 255));
        letra9.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra9.setForeground(new java.awt.Color(0, 0, 0));
        letra9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra9.setText("X");
        jPanel2.add(letra9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 110, 120));

        letra10.setEditable(false);
        letra10.setBackground(new java.awt.Color(255, 255, 255));
        letra10.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra10.setForeground(new java.awt.Color(0, 0, 0));
        letra10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra10.setText("X");
        letra10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra10ActionPerformed(evt);
            }
        });
        jPanel2.add(letra10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 110, 120));

        letra11.setEditable(false);
        letra11.setBackground(new java.awt.Color(255, 255, 255));
        letra11.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra11.setForeground(new java.awt.Color(0, 0, 0));
        letra11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra11.setText("X");
        letra11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra11ActionPerformed(evt);
            }
        });
        jPanel2.add(letra11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 110, 120));

        letra12.setEditable(false);
        letra12.setBackground(new java.awt.Color(255, 255, 255));
        letra12.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra12.setForeground(new java.awt.Color(0, 0, 0));
        letra12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra12.setText("X");
        letra12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra12ActionPerformed(evt);
            }
        });
        jPanel2.add(letra12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 110, 120));

        letra13.setEditable(false);
        letra13.setBackground(new java.awt.Color(255, 255, 255));
        letra13.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra13.setForeground(new java.awt.Color(0, 0, 0));
        letra13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra13.setText("X");
        letra13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra13ActionPerformed(evt);
            }
        });
        jPanel2.add(letra13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 110, 120));

        letra14.setEditable(false);
        letra14.setBackground(new java.awt.Color(255, 255, 255));
        letra14.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra14.setForeground(new java.awt.Color(0, 0, 0));
        letra14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra14.setText("X");
        letra14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra14ActionPerformed(evt);
            }
        });
        jPanel2.add(letra14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 110, 120));

        letra15.setEditable(false);
        letra15.setBackground(new java.awt.Color(255, 255, 255));
        letra15.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra15.setForeground(new java.awt.Color(0, 0, 0));
        letra15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra15.setText("X");
        letra15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra15ActionPerformed(evt);
            }
        });
        jPanel2.add(letra15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 110, 120));

        letra16.setEditable(false);
        letra16.setBackground(new java.awt.Color(255, 255, 255));
        letra16.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra16.setForeground(new java.awt.Color(0, 0, 0));
        letra16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra16.setText("X");
        letra16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra16ActionPerformed(evt);
            }
        });
        jPanel2.add(letra16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 110, 120));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 440, 480));

        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        jList1.setBackground(new java.awt.Color(255, 255, 255));
        jList1.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 110, 230));

        jScrollPane2.setForeground(new java.awt.Color(0, 0, 0));

        jList2.setBackground(new java.awt.Color(255, 255, 255));
        jList2.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jList2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 110, 230));

        Exit.setBackground(new java.awt.Color(204, 0, 0));
        Exit.setText("X");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 60, -1));

        New_palabra.setBackground(new java.awt.Color(255, 255, 255));
        New_palabra.setForeground(new java.awt.Color(0, 0, 0));
        New_palabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_palabraActionPerformed(evt);
            }
        });
        jPanel1.add(New_palabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 590, 200, -1));

        Buscar.setBackground(new java.awt.Color(255, 255, 255));
        Buscar.setForeground(new java.awt.Color(0, 0, 0));
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 590, -1, -1));

        iniciar.setBackground(new java.awt.Color(255, 255, 255));
        iniciar.setForeground(new java.awt.Color(0, 0, 0));
        iniciar.setText("Iniciar");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        jPanel1.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 410, 100, 30));

        DFS.setBackground(new java.awt.Color(255, 255, 255));
        DFS.setForeground(new java.awt.Color(0, 0, 0));
        DFS.setText("DFS");
        DFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFSActionPerformed(evt);
            }
        });
        jPanel1.add(DFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, -1, -1));

        BFS.setBackground(new java.awt.Color(255, 255, 255));
        BFS.setForeground(new java.awt.Color(0, 0, 0));
        BFS.setText("BFS");
        BFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFSActionPerformed(evt);
            }
        });
        jPanel1.add(BFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 340, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Depth First Search");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 220, 110, 20));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Breadth First Search");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 210, 120, 20));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Palabras");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 80, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("Este metodo se encarga de leer\ntodas las letras que se encuentran \njunto a la primera  de las mismas, \npara buscar una combinacion \nque cree una palabra y luego siga \na la siguiente letra.");
        jTextArea1.setToolTipText("");
        jPanel1.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 230, 210, 110));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea2.setRows(5);
        jTextArea2.setText("Puedes escribir una palabra que no se encuentre en el diccionario \npara que el programa lo busque, y a su vez, lo agregara al mismo. \nRECUERDA \nUna palabra valida tiene minimo 3 y maximo 4 letras");
        jPanel1.add(jTextArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, -1, 90));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Tiempo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, 20));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Escribe una palabra:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 570, -1, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Elija el metodo de busqueda");
        jLabel10.setToolTipText("");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 320, -1));

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea3.setRows(5);
        jTextArea3.setText("Este metodo lee toda la\nrama de una de las letras, \ny luego las demas ramas, \nantes de ir a la siguiente\n letras.");
        jPanel1.add(jTextArea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 240, 160, 90));

        m_b.setForeground(new java.awt.Color(0, 0, 0));
        m_b.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        m_b.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(m_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 370, 230, 30));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Metodo Selecionado:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 370, 130, 30));

        next.setBackground(new java.awt.Color(255, 255, 255));
        next.setForeground(new java.awt.Color(0, 0, 0));
        next.setText("siguiente");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 680, -1, -1));

        Alerta.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        Alerta.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Alerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 660, 1060, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/v2.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void letra16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra16ActionPerformed

    private void letra15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra15ActionPerformed

    private void letra14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra14ActionPerformed

    private void letra13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra13ActionPerformed

    private void letra12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra12ActionPerformed

    private void letra11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra11ActionPerformed

    private void letra10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra10ActionPerformed

    private void letra8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra8ActionPerformed

    private void letra7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra7ActionPerformed

    private void letra6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra6ActionPerformed

    private void letra5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra5ActionPerformed

    private void letra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra4ActionPerformed

    private void New_palabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_palabraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_New_palabraActionPerformed
    
    /**
     * Este metodo se activa al precionar el boton inciar
     * Este metodo se encarga de llamar a las clases DFS o BFs para hacer la busqueda de las palabras 
     * @param evt 
     */
    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        // TODO add your handling code here:
        String[] palabras = null;
        double[] time = null ;
        if(metodo.equals("DFS") || metodo.equals("BFS")){
            if(metodo.equals("DFS") ){
                DFS buscador = new DFS(s_l,v1.get_palabras());
                palabras = buscador.get_palabras();
                time = buscador.get_time();
            }else if(metodo.equals("BFS")){
                BFS buscador = new BFS(s_l,v1.get_palabras());
                palabras = buscador.get_palabras();
                time = buscador.get_time();
            }
            
        }else{
            this.m_b.setText("ERROR. No se selecciono ningun metodo");
        }
        boolean x = false;
        for (int i = 0; i < 7; i++) {
            if(palabras[i]!=null){
                x = true;
            }
        }
        if(x == true){
            this.mostrar_tiempo(time);
            this.mostrar_palabras(palabras);
            this.colores(false);
            m_b.setText("");
            metodo = "";
        }else{
            Alerta.setText("No se encontraron palabras en esta sopa de letras, haga click en siguiente para hacer uno nuevo");
        }
        
    }//GEN-LAST:event_iniciarActionPerformed
    
    /**
     * metodo que se activa al precionar el boton Exit
     * Este metodo se encarga de cerrar el programa
     * @param evt 
     */
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void letra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra3ActionPerformed

    private void letra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra2ActionPerformed
    
    /**
     * Este metodo se activar al precionar el boton Buscar
     * Este metodo se encarga de buscar la palabra escrita por el usuario
     * @param evt 
     */
    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        String x = this.New_palabra.getText().toUpperCase();
        boolean aux = true;
        for (int i = 0; i < v1.get_palabras().Tamaño(); i++) {
            if(v1.get_palabras().Datos(i).equals(x)){
                this.Alerta.setText("Ya se encuentra en el diccionario la palabra.");
                aux = false;
            }
        }
        if(aux == true ){
            if(x.length() < 3 || x.length() >4){
                if (x.equals("")){
                    this.Alerta.setText("Error. No se ha escribio ninguna palabra");
                }else{
                    this.Alerta.setText("Error. Tamaño de la palabra es invalida");
                }
            }else{
                String[] palabras = null;
                double[] time = null ;
                if (metodo.equals("")) {
                    this.Alerta.setText("Error. porfavor elija el metodo de busqueda y vuelva a escribir la palabra");
                }else{
                    if (metodo.equals("DFS")) {
                        DFS buscador = new DFS(s_l,x);
                        palabras = buscador.get_palabras();
                        time = buscador.get_time();
                        this.colores(true);
                        buscador.Visitar();
                        
                        
                        
                    }else if (metodo.equals("BFS")) {
                        BFS buscador = new BFS(s_l,x);
                        palabras = buscador.get_palabras();
                        time = buscador.get_time();
                        this.colores(true);
                        buscador.Visitar();
                        Graph grafo =buscador.get_grafo();
                        if(palabras[0]!=null){
                            this.setVisible(false);
                            Mostrar_Busqueda v3 = new Mostrar_Busqueda(this, grafo);
                        }
                    }
                    
                    if(palabras[0]!=null){
                        this.mostrar_palabras(palabras);
                        this.mostrar_tiempo(time);
                        Alerta.setText("Se encontro la palabra");
                        m_b.setText("");
                        metodo = "";
                    }else{
                        Alerta.setText("No se encontro la palabra");
                    }
                }
            }
        }
        this.New_palabra.setText("");
    }//GEN-LAST:event_BuscarActionPerformed
    
    /**
     * Este metodo se activa cuando el usario preciona el boton DFS
     * Este metodo se encarga de seleccionar el metodo de  busqueda DFS de las palabras
     * @param evt 
     */
    private void DFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DFSActionPerformed
        // TODO add your handling code here:
        metodo = "DFS";
        m_b.setText("Depth First Search");        
    }//GEN-LAST:event_DFSActionPerformed
    
    /**
     * Este metodo se activa cuando el usario preciona el boton BFS
     * Este metodo se encarga de seleccionar el metodo de  busqueda BFS de las palabras
     * @param evt 
     */
    private void BFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFSActionPerformed
        // TODO add your handling code here:
        metodo = "BFS";
        m_b.setText("Breath First Search");  
    }//GEN-LAST:event_BFSActionPerformed
    
    /**
     * Este metodo se activa al precionar el boton next
     * Este metodo se encarga de crear una nueva sopa de letras
     * @param evt 
     */
    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        JTextField[] aux = {this.letra1, this.letra2, this.letra3, this.letra4, this.letra5, this.letra6,this.letra7, this.letra8, this.letra9, this.letra10, this.letra11, this.letra12, this.letra13, this.letra14, this.letra15, this.letra16};
        for (int i = 0; i < 16; i++) {
            if (s_l.get_vertice(i).get_status()==true) {
                aux[i].setBackground(Color.WHITE);
            }
        }
        Alerta.setText("");
        tiempo.clear();
        metodo = "";
        words.clear();
        jList1.setModel(words);
        jList2.setModel(tiempo);
        m_b.setText("");
        this.Crear_sopa_de_letras();
        
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ventana2(v1).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alerta;
    private javax.swing.JButton BFS;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton DFS;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField New_palabra;
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField letra1;
    private javax.swing.JTextField letra10;
    private javax.swing.JTextField letra11;
    private javax.swing.JTextField letra12;
    private javax.swing.JTextField letra13;
    private javax.swing.JTextField letra14;
    private javax.swing.JTextField letra15;
    private javax.swing.JTextField letra16;
    private javax.swing.JTextField letra2;
    private javax.swing.JTextField letra3;
    private javax.swing.JTextField letra4;
    private javax.swing.JTextField letra5;
    private javax.swing.JTextField letra6;
    private javax.swing.JTextField letra7;
    private javax.swing.JTextField letra8;
    private javax.swing.JTextField letra9;
    private javax.swing.JLabel m_b;
    private javax.swing.JButton next;
    private javax.swing.JLabel palabras_sopa;
    // End of variables declaration//GEN-END:variables

}
