/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sopa.de.letras;

/**
 *
 * @author Windows 10 Pro
 */
public class Ventana2 extends javax.swing.JFrame {
    private static Ventana1 v1;
    private static Lista palabras;
    private static Lista letras;
    /**
     * Creates new form ventana2, jText.setText(words);
     * @param v1
     */
    public Ventana2( Ventana1 v1) {
        initComponents();
        this.setUndecorated(true);
        this.v1 = v1;
        this.v1.setVisible(false);
        this.setVisible(true);
        this.setExtendedState(Ventana2.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.palabras = v1.get_palabras();
        this.letras = v1.get_letras();
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        palabras_sopa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        letra1 = new javax.swing.JTextField();
        letra2 = new javax.swing.JTextField();
        letra3 = new javax.swing.JTextField();
        letra4 = new javax.swing.JTextField();
        letra5 = new javax.swing.JTextField();
        letra6 = new javax.swing.JTextField();
        letra7 = new javax.swing.JTextField();
        letra8 = new javax.swing.JTextField();
        letra9 = new javax.swing.JTextField();
        letra10 = new javax.swing.JTextField();
        letra11 = new javax.swing.JTextField();
        letra12 = new javax.swing.JTextField();
        letra13 = new javax.swing.JTextField();
        letra14 = new javax.swing.JTextField();
        letra15 = new javax.swing.JTextField();
        letra16 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        palabras_sopa.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        palabras_sopa.setText("Palabras de la sopa de letras");
        palabras_sopa.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(palabras_sopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 320, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel2.setText("Sopa De Letras");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 150));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 150));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, -1, -1));
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        letra1.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra1.setText("X");
        jPanel2.add(letra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 160));

        letra2.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra2.setText("X");
        letra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra2ActionPerformed(evt);
            }
        });
        jPanel2.add(letra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 160, 160));

        letra3.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra3.setText("X");
        letra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra3ActionPerformed(evt);
            }
        });
        jPanel2.add(letra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 160, 160));

        letra4.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra4.setText("X");
        letra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra4ActionPerformed(evt);
            }
        });
        jPanel2.add(letra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 160, 160));

        letra5.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra5.setText("X");
        letra5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra5ActionPerformed(evt);
            }
        });
        jPanel2.add(letra5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 160, 160));

        letra6.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra6.setText("X");
        letra6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra6ActionPerformed(evt);
            }
        });
        jPanel2.add(letra6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 160, 160));

        letra7.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra7.setText("X");
        letra7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra7ActionPerformed(evt);
            }
        });
        jPanel2.add(letra7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 160, 160));

        letra8.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra8.setText("X");
        letra8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra8ActionPerformed(evt);
            }
        });
        jPanel2.add(letra8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 160, 160));

        letra9.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra9.setText("X");
        jPanel2.add(letra9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 160, 160));

        letra10.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra10.setText("X");
        letra10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra10ActionPerformed(evt);
            }
        });
        jPanel2.add(letra10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 160, 160));

        letra11.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra11.setText("X");
        letra11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra11ActionPerformed(evt);
            }
        });
        jPanel2.add(letra11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 160, 160));

        letra12.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra12.setText("X");
        letra12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra12ActionPerformed(evt);
            }
        });
        jPanel2.add(letra12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 160, 160));

        letra13.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra13.setText("X");
        letra13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra13ActionPerformed(evt);
            }
        });
        jPanel2.add(letra13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 160, 160));

        letra14.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra14.setText("X");
        letra14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra14ActionPerformed(evt);
            }
        });
        jPanel2.add(letra14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 160, 160));

        letra15.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra15.setText("X");
        letra15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra15ActionPerformed(evt);
            }
        });
        jPanel2.add(letra15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 160, 160));

        letra16.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra16.setText("X");
        letra16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra16ActionPerformed(evt);
            }
        });
        jPanel2.add(letra16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 160, 160));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 640, 640));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1920, 1110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void letra16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra16ActionPerformed

    private void letra15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra15ActionPerformed

    private void letra14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra14ActionPerformed

    private void letra13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra13ActionPerformed

    private void letra12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra12ActionPerformed

    private void letra11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra11ActionPerformed

    private void letra10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra10ActionPerformed

    private void letra8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra8ActionPerformed

    private void letra7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra7ActionPerformed

    private void letra6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra6ActionPerformed

    private void letra5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra5ActionPerformed

    private void letra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra4ActionPerformed

    private void letra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra3ActionPerformed

    private void letra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField letra1;
    private javax.swing.JTextField letra10;
    private javax.swing.JTextField letra11;
    private javax.swing.JTextField letra12;
    private javax.swing.JTextField letra13;
    private javax.swing.JTextField letra14;
    private javax.swing.JTextField letra15;
    private javax.swing.JTextField letra16;
    private javax.swing.JTextField letra2;
    private javax.swing.JTextField letra3;
    private javax.swing.JTextField letra4;
    private javax.swing.JTextField letra5;
    private javax.swing.JTextField letra6;
    private javax.swing.JTextField letra7;
    private javax.swing.JTextField letra8;
    private javax.swing.JTextField letra9;
    private javax.swing.JLabel palabras_sopa;
    // End of variables declaration//GEN-END:variables
}
