/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sopa.de.letras;
import javax.swing.JFrame;
/**
 *
 * @author Windows 10 Pro
 */
public class Ventana2 extends javax.swing.JFrame {
    private static Ventana1 v1;
    private static Lista palabras;
    private static Lista letras;
    private static Grafo s_l;
    private static int[] tiempo;
    private static String[] words;
    /**
     * Creates new form ventana2, jText.setText(words);
     * @param v1
     */
    public Ventana2( Ventana1 v1) {
        initComponents();
        this.v1 = v1;
        this.palabras = v1.get_palabras();
        this.letras = v1.get_letras();
        this.setVisible(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setResizable(false);
        this.setUndecorated(true);
        this.randomizar_sopa_de_letras();
        
    }
    
    private void randomizar_sopa_de_letras() {
        double aleatorio = Math.random()*10;
        while(aleatorio > 4){
            aleatorio = Math.random()*10;
        }
        int aux = (int) aleatorio;
        Lista y = new Lista();
        for (int i = 0; i < aux; i++) {
            double z = Math.random()*10;
            while(z > palabras.Tamaño()){
                z = Math.random()*10;
            }
           int x = (int)z;
           words[i] = palabras.Datos(x);
           y.Insertar(palabras.Datos(x));
        }
        s_l = new Grafo(letras,y);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        palabras_sopa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        letra1 = new javax.swing.JTextField();
        letra2 = new javax.swing.JTextField();
        letra3 = new javax.swing.JTextField();
        letra4 = new javax.swing.JTextField();
        letra5 = new javax.swing.JTextField();
        letra6 = new javax.swing.JTextField();
        letra7 = new javax.swing.JTextField();
        letra8 = new javax.swing.JTextField();
        letra9 = new javax.swing.JTextField();
        letra10 = new javax.swing.JTextField();
        letra11 = new javax.swing.JTextField();
        letra12 = new javax.swing.JTextField();
        letra13 = new javax.swing.JTextField();
        letra14 = new javax.swing.JTextField();
        letra15 = new javax.swing.JTextField();
        letra16 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("sopa de letras");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Sopa De Letras");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 150));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 150));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        palabras_sopa.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        palabras_sopa.setForeground(new java.awt.Color(0, 0, 0));
        palabras_sopa.setText("Palabras de la Sopa de Letras");
        palabras_sopa.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(palabras_sopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 340, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        letra1.setEditable(false);
        letra1.setBackground(new java.awt.Color(255, 255, 255));
        letra1.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra1.setForeground(new java.awt.Color(0, 0, 0));
        letra1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra1.setText("X");
        jPanel2.add(letra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 120));

        letra2.setEditable(false);
        letra2.setBackground(new java.awt.Color(255, 255, 255));
        letra2.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra2.setForeground(new java.awt.Color(0, 0, 0));
        letra2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra2.setText("X");
        letra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra2ActionPerformed(evt);
            }
        });
        jPanel2.add(letra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 110, 120));

        letra3.setEditable(false);
        letra3.setBackground(new java.awt.Color(255, 255, 255));
        letra3.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra3.setForeground(new java.awt.Color(0, 0, 0));
        letra3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra3.setText("X");
        letra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra3ActionPerformed(evt);
            }
        });
        jPanel2.add(letra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 110, 120));

        letra4.setEditable(false);
        letra4.setBackground(new java.awt.Color(255, 255, 255));
        letra4.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra4.setForeground(new java.awt.Color(0, 0, 0));
        letra4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra4.setText("X");
        letra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra4ActionPerformed(evt);
            }
        });
        jPanel2.add(letra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 110, 120));

        letra5.setEditable(false);
        letra5.setBackground(new java.awt.Color(255, 255, 255));
        letra5.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra5.setForeground(new java.awt.Color(0, 0, 0));
        letra5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra5.setText("X");
        letra5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra5ActionPerformed(evt);
            }
        });
        jPanel2.add(letra5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 110, 120));

        letra6.setEditable(false);
        letra6.setBackground(new java.awt.Color(255, 255, 255));
        letra6.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra6.setForeground(new java.awt.Color(0, 0, 0));
        letra6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra6.setText("X");
        letra6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra6ActionPerformed(evt);
            }
        });
        jPanel2.add(letra6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 110, 120));

        letra7.setEditable(false);
        letra7.setBackground(new java.awt.Color(255, 255, 255));
        letra7.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra7.setForeground(new java.awt.Color(0, 0, 0));
        letra7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra7.setText("X");
        letra7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra7ActionPerformed(evt);
            }
        });
        jPanel2.add(letra7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 110, 120));

        letra8.setEditable(false);
        letra8.setBackground(new java.awt.Color(255, 255, 255));
        letra8.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra8.setForeground(new java.awt.Color(0, 0, 0));
        letra8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra8.setText("X");
        letra8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra8ActionPerformed(evt);
            }
        });
        jPanel2.add(letra8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 110, 120));

        letra9.setEditable(false);
        letra9.setBackground(new java.awt.Color(255, 255, 255));
        letra9.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra9.setForeground(new java.awt.Color(0, 0, 0));
        letra9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra9.setText("X");
        jPanel2.add(letra9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 110, 120));

        letra10.setEditable(false);
        letra10.setBackground(new java.awt.Color(255, 255, 255));
        letra10.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra10.setForeground(new java.awt.Color(0, 0, 0));
        letra10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra10.setText("X");
        letra10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra10ActionPerformed(evt);
            }
        });
        jPanel2.add(letra10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 110, 120));

        letra11.setEditable(false);
        letra11.setBackground(new java.awt.Color(255, 255, 255));
        letra11.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra11.setForeground(new java.awt.Color(0, 0, 0));
        letra11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra11.setText("X");
        letra11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra11ActionPerformed(evt);
            }
        });
        jPanel2.add(letra11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 110, 120));

        letra12.setEditable(false);
        letra12.setBackground(new java.awt.Color(255, 255, 255));
        letra12.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra12.setForeground(new java.awt.Color(0, 0, 0));
        letra12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra12.setText("X");
        letra12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra12ActionPerformed(evt);
            }
        });
        jPanel2.add(letra12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 110, 120));

        letra13.setEditable(false);
        letra13.setBackground(new java.awt.Color(255, 255, 255));
        letra13.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra13.setForeground(new java.awt.Color(0, 0, 0));
        letra13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra13.setText("X");
        letra13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra13ActionPerformed(evt);
            }
        });
        jPanel2.add(letra13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 110, 120));

        letra14.setEditable(false);
        letra14.setBackground(new java.awt.Color(255, 255, 255));
        letra14.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra14.setForeground(new java.awt.Color(0, 0, 0));
        letra14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra14.setText("X");
        letra14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra14ActionPerformed(evt);
            }
        });
        jPanel2.add(letra14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 110, 120));

        letra15.setEditable(false);
        letra15.setBackground(new java.awt.Color(255, 255, 255));
        letra15.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra15.setForeground(new java.awt.Color(0, 0, 0));
        letra15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra15.setText("X");
        letra15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra15ActionPerformed(evt);
            }
        });
        jPanel2.add(letra15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 110, 120));

        letra16.setEditable(false);
        letra16.setBackground(new java.awt.Color(255, 255, 255));
        letra16.setFont(new java.awt.Font("sansserif", 0, 70)); // NOI18N
        letra16.setForeground(new java.awt.Color(0, 0, 0));
        letra16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra16.setText("X");
        letra16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra16ActionPerformed(evt);
            }
        });
        jPanel2.add(letra16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 110, 120));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 440, 480));

        jList1.setBackground(new java.awt.Color(255, 255, 255));
        jList1.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 80, 420));

        jList2.setBackground(new java.awt.Color(255, 255, 255));
        jList2.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jList2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 80, 420));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 60, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("Escribe una palabra:");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 200, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Buscar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Iniciar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 440, 100, 30));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("DFS");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 410, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("BFS");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 410, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Depth First Search");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 110, 20));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Breadth First Search");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 260, 120, 20));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Elija el metodo de busqueda");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 190, 240, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tiempo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, 20));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Palabras");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 80, -1));

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("Este metodo se encarga de\nleer todas las letras que se \nencuentran junto a la primera \nde las mismas, para buscar \nuna combinacion que cree \nuna palabra y luego siga a la \nsiguiente letra.");
        jTextArea1.setToolTipText("");
        jPanel1.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 280, 180, 130));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea2.setRows(5);
        jTextArea2.setText("Este metodo lee toda la\nrama de una de las letras, \ny luego las demas ramas, \nantes de ir a la siguiente\n letras.");
        jPanel1.add(jTextArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 320, 160, 90));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Existe 2 metodos diferentes con el cual se puede resolver la sopa de letras.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, 420, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void letra16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra16ActionPerformed

    private void letra15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra15ActionPerformed

    private void letra14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra14ActionPerformed

    private void letra13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra13ActionPerformed

    private void letra12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra12ActionPerformed

    private void letra11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra11ActionPerformed

    private void letra10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra10ActionPerformed

    private void letra8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra8ActionPerformed

    private void letra7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra7ActionPerformed

    private void letra6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra6ActionPerformed

    private void letra5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra5ActionPerformed

    private void letra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void letra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra3ActionPerformed

    private void letra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField letra1;
    private javax.swing.JTextField letra10;
    private javax.swing.JTextField letra11;
    private javax.swing.JTextField letra12;
    private javax.swing.JTextField letra13;
    private javax.swing.JTextField letra14;
    private javax.swing.JTextField letra15;
    private javax.swing.JTextField letra16;
    private javax.swing.JTextField letra2;
    private javax.swing.JTextField letra3;
    private javax.swing.JTextField letra4;
    private javax.swing.JTextField letra5;
    private javax.swing.JTextField letra6;
    private javax.swing.JTextField letra7;
    private javax.swing.JTextField letra8;
    private javax.swing.JTextField letra9;
    private javax.swing.JLabel palabras_sopa;
    // End of variables declaration//GEN-END:variables

}
