/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sopa.de.letras;
import javax.swing.JFileChooser ;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Windows 10 Pro
 */
public class Ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form Elegir_Diccionario
     */
    
    private int retorno;
    private File Archivo;
    private FileReader Texto;
    private BufferedReader lector;
    private Lista palabras = new Lista ();
    private Lista Letras = new Lista();
    
    /**
     *
     */
    public Ventana1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Search = new javax.swing.JButton();
        Continue = new javax.swing.JButton();
        jText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Search.setText("Buscador");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        Continue.setText("Continuar");
        Continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueActionPerformed(evt);
            }
        });
        jPanel1.add(Continue, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        jText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextActionPerformed(evt);
            }
        });
        jPanel1.add(jText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 270, -1));

        jLabel1.setText("Ingrese el archivo con el diccionario.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 300, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        JFileChooser Buscador = new JFileChooser();
        Buscador.setDialogTitle("Buscar Archivo");
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("letras","txt"); 
        Buscador.setFileFilter(filter);
        Buscador.setFileSelectionMode(JFileChooser.FILES_ONLY);
        retorno = Buscador.showOpenDialog(this);
        
        if (retorno == JFileChooser.APPROVE_OPTION){
            Archivo = Buscador.getSelectedFile();
            jText.setText(Archivo.getPath());
            this.setVisible(true);  
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void jTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextActionPerformed

    private void ContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueActionPerformed
        // TODO add your handling code here:
         
        if (retorno == JFileChooser.APPROVE_OPTION){
            try {
                // TODO add your handling code here:
                String Direccion = Archivo.getPath();
                Texto = new FileReader(Direccion);
                
                    
                lector = new BufferedReader(Texto);
                String cadena;
                boolean firstime = true;
                boolean firstime1 = true;
                while ((cadena = lector.readLine())!= null){
                    if ((cadena.equals("dic"))== false){
                        
                        if(cadena.equals("/dic")== false){
                            if(firstime == true){
                                palabras.PreInsertar(cadena);
                                firstime = false;
                            }else{
                                palabras.Insertar(cadena);         
                            }
                            
                        }else{
                            break;
                         }               
                    }
                        
                }
                while ((cadena = lector.readLine())!= null){    
                    if(cadena.equals("tab")){
                        
                        if(cadena.equals("/tab")== false){
                            String[] aux = cadena.split(",");
                            for (int i = 0; i < aux.length; i++) {
                            
                                if(firstime1 == true){
                                    Letras.PreInsertar(aux[i]);
                                    firstime1 = false;
                                }else{
                                    Letras.Insertar(aux[i]);
                                }
                            }
                        }else{
                            break;
                        }
                    }
                } 
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Ventana1.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Ventana1.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
        menu v2 = new menu(this);
    }//GEN-LAST:event_ContinueActionPerformed

    /**
     * @return 
     */
    public Lista get_palabras(){
        return palabras; 
    }

    /**
     *
     * @return
     */
    public Lista get_letras(){    
        return Letras; 
    }

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Continue;
    private javax.swing.JButton Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jText;
    // End of variables declaration//GEN-END:variables


}


